### ISSUE TITLE
非持续定位类软件模拟定位异常

### ISSUE THREAD

**Issue by onegithuber** [fuqiuluo/Portal#2]
测试了几款app都没有定位权限，获取定位权限失败

**Comment by fuqiuluo** [comment]
举个例子，有哪几个？您有LSPosed框架吗？是否启用了模块？是否在模块中开启了模拟？您的设备机型是什么？

**Comment by onegithuber** [comment]
> 举个例子，有哪几个？您有LSPosed框架吗？是否启用了模块？是否在模块中开启了模拟？您的设备机型是什么？

测试机型为pixel 6,有LSPosed 模块，启用了模块，在模块中也开启了模拟。测了滴滴和美团

**Comment by fuqiuluo** [comment]
你说的这两个软件只获取瞬间的定位，而Portal只会模拟持续定位

**Comment by onegithuber** [comment]
可以了，定位服务不知道怎么被关闭了。
