### ISSUE TITLE
gradle未配置环境

### ISSUE THREAD

**Issue by miao1986** [fuqiuluo/Portal#4]
恩，如题，载入as最后提示gradle未配置环境的意思。

**Comment by fuqiuluo** [comment]
截图

**Comment by miao1986** [comment]
有可能我自己的问题，git项目后自动下载的AGP版本是最新的忘记那个了，然后提示说我Android Studio版本不支持，要降级AGP.开始以为是gradle版本太低了。我升级到8.10.1还是提示一样的问题。![IMG20241031014841.jpg](https://github.com/user-attachments/assets/d2ff27ef-1e7d-430a-ab96-fb2f2cea9e7d)

因为删除了项目。错误没拍照。重新构建太费时间。

**Comment by fuqiuluo** [comment]
> 有可能我自己的问题，git项目后自动下载的AGP版本是最新的忘记那个了，然后提示说我Android Studio版本不支持，要降级AGP.开始以为是gradle版本太低了。我升级到8.10.1还是提示一样的问题。![IMG20241031014841.jpg](https://private-user-images.githubusercontent.com/44361134/381672672-d2ff27ef-1e7d-430a-ab96-fb2f2cea9e7d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMTEzOTAsIm5iZiI6MTczMDMxMTA5MCwicGF0aCI6Ii80NDM2MTEzNC8zODE2NzI2NzItZDJmZjI3ZWYtMWU3ZC00MzBhLWFiOTYtZmIyZjJjZWE5ZTdkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE3NTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkY2NiNDA3NTlhZGNkZmYwYjhlNTQwMDdmZThhY2I4OTM5MDIxODk1Y2MyM2JmMDU0NzIwNDBkZmJmMzc1ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wD6zw16N37f23AJG4_KeHIZp5lEGogR4Yv8e6If2chY)
> 
> 因为删除了项目。错误没拍照。重新构建太费时间。

和Android Studio关系不大，可能是gradle8.9要求的java版本比较高导致的？我不记得我怎么配置的了 我的环境是gradle 8.9 + openjdk 21

**Comment by miao1986** [comment]
那么问题应该找到了，我Java版本是17.感谢开发大佬帮我解决问题。
