### ISSUE TITLE
功能增加建议

### ISSUE THREAD

**Issue by miao1986** [fuqiuluo/Portal#8]
有个项目叫MockGps他的悬浮按钮功能实在是太方便了。不知道大佬有无兴趣借鉴下。

**Comment by fuqiuluo** [comment]
截图看看是什么东西，没听懂

**Comment by miao1986** [comment]
https://github.com/liujiayu5566/MockGps
这位大佬的。

**Comment by fuqiuluo** [comment]
额😑，没空写这个东西

**Comment by miao1986** [comment]
大佬，你你你不睡觉的嘛？
